[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
lockmysol = "5b6JMVrHatTdGFnHtKb2iuBquDmspYsPq1HLKifS8QHA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mike/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
